### ISSUE TITLE
ImportError: cannot import name '_Union' from 'typing'

### ISSUE THREAD

**Issue by Parenty** [qase-tms/qase-pytest#1]
Please see the following errors. I`m use python 3.9. 
Found a [similar issue](https://github.com/aws/aws-cdk/issues/11102) but still don't understand how to solve it

```Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.4\plugins\python-ce\helpers\pycharm\_jb_pytest_runner.py", line 43, in <module>
    sys.exit(pytest.main(args, plugins_to_load + [Plugin]))
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\_pytest\config\__init__.py", line 1280, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\_pytest\config\__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "c:\users\reald\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\reald\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\qaseio\pytest\__init__.py", line 10, in <module>
    from qaseio.pytest.plugin import QasePytestPluginSingleton
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\qaseio\pytest\plugin.py", line 10, in <module>
    from qaseio.client import QaseApi
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\qaseio\client\__init__.py", line 10, in <module>
    from apitist.hooks import (
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\apitist\hooks.py", line 8, in <module>
    from apitist.utils import is_attrs_class
  File "C:\Work\student_lk_autotests\venv\lib\site-packages\apitist\utils.py", line 86, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (c:\users\reald\appdata\local\programs\python\python39\lib\typing.py)```

**Comment by tirkarthi** [comment]
This seems to have been fixed in apitist : https://github.com/zeburek/python-apitist/commit/51e2cdafa77d8ed9e5b276a5260c71d5e55c242d

**Comment by Parenty** [comment]
Thank you
